export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  images: string[];
  description: string;
  color: string;
  type: string;
  size: string[];
  popularity: number;
  inStock?: boolean;
  isNew?: boolean;
  isSale?: boolean;
  rating?: number;
  reviewCount?: number;
}

const HOODIE_IMAGE = "/_static/products/hoodie.png";

// Duplicate hoodie image for all products (4 images each)
const hoodieImages = Array(4).fill(HOODIE_IMAGE);

export const products: Product[] = [
  {
    id: "1",
    name: "Unidoka Hoodie",
    slug: "unidoka-hoodie",
    price: 45,
    images: hoodieImages,
    description: "Organic cotton, embroidered logo, unisex fit.",
    color: "Green",
    type: "Apparel",
    size: ["S", "M", "L", "XL"],
    popularity: 120,
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: "2",
    name: "Unidoka Mug",
    slug: "unidoka-mug",
    price: 25,
    images: hoodieImages,
    description: "Ceramic, 12 oz, dishwasher safe.",
    color: "White",
    type: "Home",
    size: ["One Size"],
    popularity: 85,
    inStock: true,
    rating: 4.6,
    reviewCount: 18,
  },
  {
    id: "3",
    name: "Unidoka Notebook",
    slug: "unidoka-notebook",
    price: 18,
    images: hoodieImages,
    description: "160 pages, dot grid, lay-flat binding.",
    color: "Black",
    type: "Stationery",
    size: ["A5"],
    popularity: 200,
    inStock: false,
    isSale: true,
    rating: 4.9,
    reviewCount: 12,
  },
  {
    id: "4",
    name: "Unidoka Cap",
    slug: "unidoka-cap",
    price: 32,
    images: hoodieImages,
    description: "Wool blend, adjustable strap, embroidered.",
    color: "Navy",
    type: "Apparel",
    size: ["One Size"],
    popularity: 65,
    inStock: true,
    isNew: true,
    rating: 4.3,
    reviewCount: 9,
  },
  {
    id: "5",
    name: "Unidoka Tote Bag",
    slug: "unidoka-tote-bag",
    price: 28,
    images: hoodieImages,
    description: "Canvas, reinforced handles, 15L capacity.",
    color: "Beige",
    type: "Accessories",
    size: ["One Size"],
    popularity: 90,
    inStock: true,
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: "6",
    name: "Unidoka Phone Case",
    slug: "unidoka-phone-case",
    price: 15,
    images: hoodieImages,
    description: "Silicone, shockproof, wireless charging compatible.",
    color: "Clear",
    type: "Accessories",
    size: ["iPhone 15", "iPhone 16"],
    popularity: 110,
    inStock: true,
    isNew: true,
    rating: 4.5,
    reviewCount: 22,
  },
  {
    id: "7",
    name: "Unidoka Water Bottle",
    slug: "unidoka-water-bottle",
    price: 35,
    images: hoodieImages,
    description: "Stainless steel, vacuum insulated, 32 oz.",
    color: "Silver",
    type: "Home",
    size: ["32 oz"],
    popularity: 75,
    inStock: true,
    rating: 4.4,
    reviewCount: 10,
  },
  {
    id: "8",
    name: "Unidoka Desk Mat",
    slug: "unidoka-desk-mat",
    price: 20,
    images: hoodieImages,
    description: "Large, water-resistant, non-slip base.",
    color: "Dark Gray",
    type: "Office",
    size: ["900x400mm"],
    popularity: 130,
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 28,
  },
  {
    id: "9",
    name: "Unidoka Sticker Pack",
    slug: "unidoka-sticker-pack",
    price: 8,
    images: hoodieImages,
    description: "Set of 10 vinyl stickers, weatherproof.",
    color: "Multicolor",
    type: "Stationery",
    size: ["Assorted"],
    popularity: 220,
    inStock: true,
    rating: 4.2,
    reviewCount: 45,
  },
  {
    id: "10",
    name: "Unidoka Socks",
    slug: "unidoka-socks",
    price: 12,
    images: hoodieImages,
    description: "Organic cotton, reinforced heel and toe.",
    color: "Black",
    type: "Apparel",
    size: ["S", "M", "L"],
    popularity: 60,
    inStock: true,
    isSale: true,
    rating: 4.0,
    reviewCount: 8,
  },
];
